### ISSUE TITLE
Error message in Console

### ISSUE THREAD

**Issue by hendelmasad** [anvil-vtt/FateX#100]
As near as I can tell, everything still works but when I checked the console on an unrelated matter I found the error messages copied below. At the very bottom it lists the Fate X system. It might be unrelated to your fine ruleset but I wouldn't know therefore, at a glance, does this look like a bug in the ruleset?

foundry.js:747 Error: FateActor [bwK5UIduqtJpvmHE] Model Validation Errors
[FateActor.items]: Model Validation Errors
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: equipment is not a valid choice
Model Validation Errors
[BaseItem.type]: equipment is not a valid choice
Model Validation Errors
[BaseItem.type]: equipment is not a valid choice
Model Validation Errors
[BaseItem.type]: equipment is not a valid choice
Model Validation Errors
[BaseItem.type]: equipment is not a valid choice
Model Validation Errors
[BaseItem.type]: equipment is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
Model Validation Errors
[BaseItem.type]: move is not a valid choice
[Detected 1 package: system:fatex]
    at SchemaField._validateType (commons.js:4090:15)
    at SchemaField.validate (commons.js:3817:37)
    at FateActor.validate (commons.js:5470:35)
    at new DataModel (commons.js:5247:26)
    at new Document (commons.js:5786:3)
    at new BaseActor (commons.js:7133:3)
    at new ClientDocumentMixin (foundry.js:12996:5)
    at new Actor (foundry.js:16222:1)
    at new FateActor (system.js:2:140204)
    at FateActor.fromSource (commons.js:5680:14)
    at Actors._initialize (foundry.js:13835:34)
    at new DocumentCollection (foundry.js:13821:10)
    at new WorldCollection (foundry.js:14064:1)
    at new Actors (foundry.js:14224:1)
    at Game.initializeDocuments (foundry.js:7951:30)
    at Game.setupGame (foundry.js:7877:10)
    at async Game._initializeGameView (foundry.js:895

**Comment by hendelmasad** [comment]
oh I forgot, I am using V10 Build 288 on Forge, Win 10.

**Comment by PatrickBauer** [comment]
@hendelmasad Do you know if this error still persists? I didn't find any culprit and it might(!) be due to some modules which save additional data inside the systems entities.

**Comment by hendelmasad** [comment]
I haven't experienced anything like this in a while. I will check the
console when I get home.
