### ISSUE TITLE
broken descriptions in foundry v12

### ISSUE THREAD

**Issue by Licenser** [anvil-vtt/FateX#124]
**Describe the bug**

All long descriptions are only showing as `[object Promise]` in v12 Foundry

**To Reproduce**
1. create a character
3. Click on 'Extras' (or stunts)
4. Go to edit mode
6. See the Description be reduced to `[object Promise]` 
7. edit the description
8. save the description
9.  See the Description be reduced to `[object Promise]`  again

**Expected behavior**
Description texts are correctly displayed and can be edited

**Screenshots or Videos**
![image](https://github.com/anvil-vtt/FateX/assets/119093/f100a2e3-8ba2-40d0-827d-bc1b19d5f1fe)
![image](https://github.com/anvil-vtt/FateX/assets/119093/315d8164-f80a-4aba-ba48-97b3f969d5f2)
![image](https://github.com/anvil-vtt/FateX/assets/119093/7d6726bd-b9a8-4029-8766-a22552acd8c8)

**Desktop (please complete the following information):**
 - Browser Chrome based & firefox

**Additional context**

The error console shows no errors just the following warning:
```
Error: You are accessing globalThis.duplicate which must now be accessed via foundry.utils.duplicate
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14
    at Object.logCompatibilityWarning (foundry-esm.js:4598:19)
    at get (foundry-esm.js:65057:25)
    at CharacterSheet.getData (system.js:2:106817)
    at CharacterSheet._render (foundry.js:5814:29)
    at CharacterSheet._render (foundry.js:6548:17)
    at CharacterSheet._render (foundry.js:7134:17)
    at CharacterSheet._render (system.js:2:108834)
    at CharacterSheet.render (foundry.js:5769:10)
    at FateActor.render (foundry.js:10745:13)
    at FateActor.render (system.js:2:154407)
    at FateActor._onUpdateDescendantDocuments (foundry.js:11113:12)
    at FateActor._onUpdateDescendantDocuments (foundry.js:15962:11)
    at FateActor._dispatchDescendantDocumentEvents (foundry.js:11033:10)
    at #handleUpdateDocuments (foundry-esm.js:55792:15)
    at async FateItem.updateDocuments (foundry-esm.js:11384:23)
    at async FateItem.update (foundry-esm.js:11494:23)
    at async StuntSheet._onSubmit (foundry.js:6641:7)
    at async StuntSheet.saveEditor (foundry.js:6785:5)
```

**Comment by RinVindor** [comment]
Also seeing the same bug. Hopefully the system can be updated for v12 as myself and our group want to use the new features.

**Comment by PatrickBauer** [comment]
Thank you, I'll have a look at this, but can't make any promises right now 🙏
